# Generated by Django 3.1 on 2020-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=120)),
                ('phonenumber', models.IntegerField(max_length=12, unique=True)),
                ('age', models.IntegerField()),
                ('jobtitle', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=150)),
                ('skills', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=120)),
            ],
        ),
    ]
