# Generated by Django 3.1 on 2020-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_auto_20201119_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='jobtitle',
            field=models.CharField(max_length=120),
        ),
    ]
