# Generated by Django 3.1 on 2020-11-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_jobrequirements'),
        ('trainers', '0003_auto_20201119_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='jobtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.jobcreation'),
        ),
    ]
