# Generated by Django 3.1 on 2020-11-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_auto_20201119_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='applied', max_length=120),
        ),
    ]
