# Generated by Django 3.1 on 2020-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_auto_20201121_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='emailId',
            field=models.CharField(default='@gmail.com', max_length=50),
        ),
    ]
