# Generated by Django 3.1 on 2020-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_personalprofile_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('jobtitle', models.CharField(max_length=150)),
                ('expectedamount', models.IntegerField(max_length=150)),
            ],
        ),
    ]
