# Generated by Django 3.1 on 2020-11-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_jobrequirements'),
        ('trainers', '0008_trainerbidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='emailId',
        ),
        migrations.CreateModel(
            name='FinalSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('phonenumber', models.IntegerField(max_length=12, unique=True)),
                ('emailId', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=150)),
                ('skills', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('expectedamount', models.IntegerField(max_length=150)),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.jobcreation')),
            ],
        ),
    ]
