# Generated by Django 3.1 on 2020-11-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_auto_20201121_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalsubmit',
            name='jobtitle',
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
        migrations.DeleteModel(
            name='FinalSubmit',
        ),
    ]
