# Generated by Django 3.1 on 2020-11-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=120)),
                ('qualifications', models.CharField(max_length=120)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.jobcreation')),
            ],
        ),
    ]
